version: "3"
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql-for-test
    restart: unless-stopped
    ports:
      - "43306:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234
